# Generated by Django 4.1.7 on 2023-10-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_blogs',
            field=models.CharField(default='', max_length=100),
        ),
    ]
